import { Roboto_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import NextThemeProvider from "@/theme/NextThemeProvider";
import { Toaster } from "react-hot-toast";

const robotomono = Roboto_Mono({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${robotomono.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-background text-foreground">


        <NextThemeProvider>
          <Navbar />
          {children}
          <Toaster position="top-center" />
          <Footer />
        </NextThemeProvider>


      </body>
    </html>
  );
}
